[workspace]
resolver = "3"
members = ["crates/*"]

[profile.release]
lto = "thin"

# The profile that 'dist' will build with
[profile.dist]
inherits = "release"
lto = "thin"

[profile.profile]
inherits = "release"
lto = "thin"
debug = true