[package]
name = "code-to-pdf"
version = "0.1.0"
edition = "2021"

[dependencies]
genpdf = "0.2.0"
ignore = "0.4.23"
printpdf = { git = "https://github.com/fschutt/printpdf", features = ["html"] }
syntect = "5.2.0"
