[package]
name = "code-to-pdf"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "code-to-pdf"
path = "src/main.rs"

[dependencies]
argh = "0.1.13"
ignore = "0.4.23"
printpdf = { git = "https://github.com/fschutt/printpdf", features = ["html"] }
syntect = "5.2.0"
two-face = "0.4.3"
